[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error" 